baseURL = '//chenbrian.ca'
languageCode = 'en-us'
title = 'chenbrian'

# Theme to use
theme = "bettermotherfuckinghugowebsite"

# Pagination
paginate = 25
paginatePath = "page"


# enable last updated
enableGitInfo = true

# Google analytics
googleAnalytics = "G-B0ZFV4LTG2"

# Copyright
copyright = "© 2025 — Brian Chen — All rights reserved."


# Highlighting

pygmentsCodefences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsoptions = "linenos=table"
pygmentsStyle = "emacs"


# Taxonomies
[taxonomies]
tag = "tags"
category = "categories"


# Menu
[menu]
# Header
[[menu.main]]
url = "/posts/"
name = "posts"
weight = 2
[[menu.main]]
url = "https://github.com/ihasdapie"
name = "github"
weight = 3
[[menu.main]]
url = "/resume.pdf"
name = "cv"
weight = 4


# Footer
[[menu.footer]]
url = "https://github.com/ihasdapie/bettermotherfuckinghugowebsite/"
name = "Theme"
weight = 1

[[menu.footer]]
url = "https://github.com/ihasdapie"
name = "GitHub"
weight = 1

# Links format
[permalinks]
posts = "/posts/:slug/"

[params]
# Date format (default: Jan 2, 2006)
# datefmt  = "Jan 2, 2006"

[markup]
[markup.goldmark.parser]
block = true
title = true


[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true


[markup.tableOfContents]
startLevel = 2
endLevel = 3
ordered = false
